services:
  database:
   image: mysql:9.1.0
   volumes:
   - DbFiles:/var/lib/mysql
   env_file:
   - ./env/database.env
   ports:
     - 3306:3306
   healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10

volumes:
  DBfile: